// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYolCicHbku0HQe5onwcJMpdmHrfZLjs',
    appId: '1:573427618789:web:f6f3db2204ca927d0cd50c',
    messagingSenderId: '573427618789',
    projectId: 'webbinar-app',
    authDomain: 'webbinar-app.firebaseapp.com',
    storageBucket: 'webbinar-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlso01vGX8w5mt1-acO7NGDa61dhJh158',
    appId: '1:573427618789:android:448693ea7f14eb140cd50c',
    messagingSenderId: '573427618789',
    projectId: 'webbinar-app',
    storageBucket: 'webbinar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu4ef5w13PY085k-OldSRF1MRSBirvCP8',
    appId: '1:573427618789:ios:4a5f53c868ab99cb0cd50c',
    messagingSenderId: '573427618789',
    projectId: 'webbinar-app',
    storageBucket: 'webbinar-app.firebasestorage.app',
    iosBundleId: 'com.example.webinar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu4ef5w13PY085k-OldSRF1MRSBirvCP8',
    appId: '1:573427618789:ios:4a5f53c868ab99cb0cd50c',
    messagingSenderId: '573427618789',
    projectId: 'webbinar-app',
    storageBucket: 'webbinar-app.firebasestorage.app',
    iosBundleId: 'com.example.webinar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTYolCicHbku0HQe5onwcJMpdmHrfZLjs',
    appId: '1:573427618789:web:95352d36e6310b2a0cd50c',
    messagingSenderId: '573427618789',
    projectId: 'webbinar-app',
    authDomain: 'webbinar-app.firebaseapp.com',
    storageBucket: 'webbinar-app.firebasestorage.app',
  );
}
